/**
 * Boundary Policy Table v1 (Phase 8.2D-3).
 *
 * Canonical boundary metadata only: this table does not evaluate traces, enforce policy,
 * generate explanations, or connect to Smart Talk/UI.
 */

import type { BoundaryPolicyDefinition } from "./boundary-policy-types";

export const BOUNDARY_POLICY_TABLE_VERSION = "8.2d-3-boundary-policy-table-v1";

const BASE_CONSTRAINTS = ["never_render_directly", "dry_run_not_truth"] as const;

export const BOUNDARY_POLICY_TABLE_V1 = [
  {
    boundaryId: "do_not_calculate_deadline",
    category: "prohibition",
    description: "Forbids synthetic calendar deadline calculation from simulation or gate signals.",
    productionReadiness: "governance_foundation",
    consumerConstraints: [...BASE_CONSTRAINTS, "not_deadline_authority"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Always emitted by the 8.2D-1 skeleton; still metadata, not runtime enforcement."],
  },
  {
    boundaryId: "do_not_claim_enforcement",
    category: "escalation_safety",
    description: "Prevents downstream consumers from stating enforcement as fact from trap/governance signals.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "not_legal_advice", "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: [
      "Currently influenced by broad trap signals and enforcementTrapHeuristic; not production-safe until structured trap metadata exists.",
    ],
  },
  {
    boundaryId: "do_not_claim_finality",
    category: "prohibition",
    description: "Forbids claiming finality or unappealability without explicit authorized support.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "not_legal_advice", "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-0",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Defined but not emitted by the 8.2D-1 skeleton; future wiring requires finality-specific gate signals."],
  },
  {
    boundaryId: "do_not_merge_payment_and_appeal",
    category: "lane_safety",
    description: "Keeps payment and appeal lanes separate for downstream explanation planning.",
    productionReadiness: "governance_foundation",
    consumerConstraints: [...BASE_CONSTRAINTS, "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Always emitted by the 8.2D-1 skeleton as a lane-safety invariant."],
  },
  {
    boundaryId: "do_not_merge_lanes",
    category: "lane_safety",
    description: "General lane-isolation boundary for traces with trap ambiguity or triggered traps.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Currently emitted for any triggered or uncertain trap; future trap metadata should scope it by lane risk."],
  },
  {
    boundaryId: "do_not_present_dry_run_as_fact",
    category: "simulation_safety",
    description: "Forbids presenting dry-run simulation or Evidence Gates candidates as user-visible truth.",
    productionReadiness: "governance_foundation",
    consumerConstraints: BASE_CONSTRAINTS,
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Always emitted by the 8.2D-1 skeleton and should remain a permanent consumer constraint."],
  },
  {
    boundaryId: "do_not_present_speculation_as_fact",
    category: "uncertainty_preservation",
    description: "Forbids turning speculative support paths into factual statements.",
    productionReadiness: "governance_foundation",
    consumerConstraints: [...BASE_CONSTRAINTS, "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Always emitted by the 8.2D-1 skeleton; does not itself detect speculation."],
  },
  {
    boundaryId: "require_uncertainty_wording",
    category: "required_wording_constraint",
    description: "Requires a future explanation layer to preserve uncertainty rather than assert certainty.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Triggered broadly by uncertain realities, uncertain traps, or speculative metadata in the skeleton."],
  },
  {
    boundaryId: "use_relative_deadline_wording_only",
    category: "required_wording_constraint",
    description: "Requires relative deadline wording only when deadline discussion is later allowed.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "not_deadline_authority", "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-0",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Defined but not emitted by the 8.2D-1 skeleton; future wiring needs deadline-specific trace policy."],
  },
  {
    boundaryId: "mention_uncertainty_if_ocr_noisy",
    category: "conditional_advisory",
    description: "Marks that future explanation governance should mention uncertainty when structured OCR quality is noisy.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [...BASE_CONSTRAINTS, "requires_uncertainty_layer"],
    deprecated: false,
    introducedInPhase: "8.2D-0",
    intendedConsumerLayer: "explanation_governance",
    notes: ["Defined but not emitted by the 8.2D-1 skeleton; requires structured document-quality input wiring."],
  },
  {
    boundaryId: "recommend_human_review_high_risk",
    category: "escalation_recommendation",
    description: "Governance recommendation for human review context in high-risk or ambiguous traces.",
    productionReadiness: "dry_run_only",
    consumerConstraints: [
      ...BASE_CONSTRAINTS,
      "not_legal_advice",
      "requires_human_review_context",
      "requires_uncertainty_layer",
    ],
    deprecated: false,
    introducedInPhase: "8.2D-1",
    intendedConsumerLayer: "human_review_routing",
    notes: ["Canonical token after 8.2D-2B alias consolidation; not user-facing advice."],
  },
  {
    boundaryId: "recommend_human_review_for_high_risk",
    category: "escalation_recommendation",
    description: "Historical alias for human review recommendation retained only for governance metadata.",
    productionReadiness: "not_safe_for_production",
    consumerConstraints: [
      ...BASE_CONSTRAINTS,
      "not_legal_advice",
      "requires_human_review_context",
      "requires_uncertainty_layer",
    ],
    deprecated: true,
    replacementBoundaryId: "recommend_human_review_high_risk",
    introducedInPhase: "8.2D-0",
    intendedConsumerLayer: "audit_only",
    notes: [
      "Removed from ExplanationBoundary union in 8.2D-2B; never emitted by the skeleton and no production consumers existed.",
    ],
  },
] as const satisfies readonly BoundaryPolicyDefinition[];
