import type { GermanRegion, RegionConfig } from "./types";

export const REGION_CONFIG: Record<GermanRegion, RegionConfig> = {
  "baden-wuerttemberg": {
    id: "baden-wuerttemberg",
    label: "Bádensko-Württembersko",
    germanLabel: "Baden-Württemberg",
    defaultCity: "Stuttgart",
    vibe: "mixed",
    colorHint: "emerald",
    description: "Juh Nemecka, práca, rodina a stabilné mestá.",
  },
  bayern: {
    id: "bayern",
    label: "Bavorsko",
    germanLabel: "Bayern",
    defaultCity: "Mníchov",
    vibe: "nature",
    colorHint: "emerald",
    description: "Alpy, Mníchov a pokojné zázemie pre život v Nemecku.",
  },
  berlin: {
    id: "berlin",
    label: "Berlin",
    germanLabel: "Berlin",
    defaultCity: "Berlin",
    vibe: "capital",
    colorHint: "indigo",
    description: "Hlavné mesto, úrady, práca a rýchla orientácia.",
  },
  brandenburg: {
    id: "brandenburg",
    label: "Brandenbursko",
    germanLabel: "Brandenburg",
    defaultCity: "Potsdam",
    vibe: "nature",
    colorHint: "emerald",
    description: "Pokojné zázemie okolo Berlína.",
  },
  bremen: {
    id: "bremen",
    label: "Brémy",
    germanLabel: "Bremen",
    defaultCity: "Bremen",
    vibe: "urban",
    colorHint: "blue",
    description: "Menší mestský región so silnou administratívnou identitou.",
  },
  hamburg: {
    id: "hamburg",
    label: "Hamburg",
    germanLabel: "Hamburg",
    defaultCity: "Hamburg",
    vibe: "coastal",
    colorHint: "blue",
    description: "Prístav, voda a medzinárodný mestský rytmus.",
  },
  hessen: {
    id: "hessen",
    label: "Hesensko",
    germanLabel: "Hessen",
    defaultCity: "Frankfurt nad Mohanom",
    vibe: "urban",
    colorHint: "indigo",
    description: "Financie, práca a silné mestské centrum.",
  },
  "mecklenburg-vorpommern": {
    id: "mecklenburg-vorpommern",
    label: "Meklenbursko-Predpomoransko",
    germanLabel: "Mecklenburg-Vorpommern",
    defaultCity: "Schwerin",
    vibe: "coastal",
    colorHint: "teal",
    description: "More, pokoj a severonemecký životný rytmus.",
  },
  niedersachsen: {
    id: "niedersachsen",
    label: "Dolné Sasko",
    germanLabel: "Niedersachsen",
    defaultCity: "Hannover",
    vibe: "mixed",
    colorHint: "slate",
    description: "Veľký región medzi mestami, prácou a vidiekom.",
  },
  "nordrhein-westfalen": {
    id: "nordrhein-westfalen",
    label: "Severné Porýnie-Vestfálsko",
    germanLabel: "Nordrhein-Westfalen",
    defaultCity: "Düsseldorf",
    vibe: "industrial",
    colorHint: "slate",
    description: "Hustý pracovný región, úrady, mestá a infraštruktúra.",
  },
  "rheinland-pfalz": {
    id: "rheinland-pfalz",
    label: "Porýnie-Falcko",
    germanLabel: "Rheinland-Pfalz",
    defaultCity: "Mainz",
    vibe: "mixed",
    colorHint: "amber",
    description: "Pokojnejší západný región s mestami a rodinným zázemím.",
  },
  saarland: {
    id: "saarland",
    label: "Sársko",
    germanLabel: "Saarland",
    defaultCity: "Saarbrücken",
    vibe: "mixed",
    colorHint: "slate",
    description: "Menší región pri hraniciach s Francúzskom.",
  },
  sachsen: {
    id: "sachsen",
    label: "Sasko",
    germanLabel: "Sachsen",
    defaultCity: "Drážďany",
    vibe: "urban",
    colorHint: "indigo",
    description: "Mestá, história a východonemecká administratíva.",
  },
  "sachsen-anhalt": {
    id: "sachsen-anhalt",
    label: "Sasko-Anhaltsko",
    germanLabel: "Sachsen-Anhalt",
    defaultCity: "Magdeburg",
    vibe: "mixed",
    colorHint: "slate",
    description: "Stredonemecký región s pokojnejším rytmom.",
  },
  "schleswig-holstein": {
    id: "schleswig-holstein",
    label: "Šlezvicko-Holštajnsko",
    germanLabel: "Schleswig-Holstein",
    defaultCity: "Kiel",
    vibe: "coastal",
    colorHint: "teal",
    description: "Sever, more a pokojné prostredie.",
  },
  thueringen: {
    id: "thueringen",
    label: "Durínsko",
    germanLabel: "Thüringen",
    defaultCity: "Erfurt",
    vibe: "nature",
    colorHint: "emerald",
    description: "Zelené srdce Nemecka a pokojná orientácia.",
  },
};

export const GERMAN_REGIONS = Object.keys(REGION_CONFIG) as GermanRegion[];

export function getRegionConfig(region?: string | null) {
  if (!region) return null;
  return REGION_CONFIG[region as GermanRegion] ?? null;
}

